version: '3.7'

services:
  router:
    image: container-registry.oracle.com/mysql/community-router:8.0
    platform: linux/amd64
    environment:
      - MYSQL_HOST=mysql1 # MySQL Router 가 연결할 기본 MySQL 서버 호스트명
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_INNODB_CLUSTER_MEMBERS=3
      - MYSQL_CREATE_ROUTER_USER=0
    ports:
      - "6446:6446"
      - "6447:6447"
    networks:
      - innodb-cluster-net
    container_name: router
    restart: always
    depends_on:
      - mysql1
      - mysql2
      - mysql3

  mysql1:
    image: my-custom-mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    command:
      - --server-id=1
      - --log-bin=mysql-bin-1.log
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --transaction-write-set-extraction=XXHASH64
      - --binlog-checksum=NONE
      - --plugin-load=group_replication.so
    networks:
      - innodb-cluster-net
    container_name: mysql1
    restart: always

  mysql2:
    image: my-custom-mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    command:
      - --server-id=2
      - --log-bin=mysql-bin-2.log
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --transaction-write-set-extraction=XXHASH64
      - --binlog-checksum=NONE
      - --plugin-load=group_replication.so
    networks:
      - innodb-cluster-net
    container_name: mysql2
    restart: always

  mysql3:
    image: my-custom-mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3309:3306"
    command:
      - --server-id=3
      - --log-bin=mysql-bin-3.log
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --transaction-write-set-extraction=XXHASH64
      - --binlog-checksum=NONE
      - --plugin-load=group_replication.so
    networks:
      - innodb-cluster-net
    container_name: mysql3
    restart: always

networks:
  innodb-cluster-net:
    driver: bridge

